### ISSUE TITLE
Anti-Virus detection

### ISSUE THREAD

**Issue by NoAvalon** [chaldea-center/chaldea#72]
### What happened?

Hello,

it's not really a bug but today when I opened the app my Bitdefender showed me it's a virus and refused to let me have access to it. I'm certain it is a false positive but of course it would be nice not having to put an executable into exceptions for it to work. Not sure if something can be done about it.
If you're curious which ones detect it as a threat for now I uploaded it to Virustotal to see. Here are the [results](https://www.virustotal.com/gui/file/0042f969cfdbeea0355c18a83e20c4e6a6052ce2212e6c977f7cf245d463c32f/detection).

### Platform

Windows

### App Version

2.1.1 (914)

**Comment by narumi147** [comment]
Ah... It seems there is nothing I can do so far. It is built with flutter, not only flutter apps but also flutter sdk itself may be detected as virus. 
- https://github.com/flutter/flutter/issues/61997
- https://github.com/flutter/flutter/issues/95167

The virustotal website told some triggers about `wevtutil` and some other commands, cannot remind me of which package could relate to it.

At least, for descktop app(win/mac/linux), there is a way to execute commands in local shells(such as powershell/cmd), so it may be marked as harmful. Also some packages may touch some dangrous apis to make it more universal and almighty.

A possible way is to publish app in Microsoft store, which will give the app a signature to tell Windows it is safe. But that makes publish more tedious and out of my control, the further consideration is more people don't/cannot use Microsoft Store.

Since I didn't know much about virus and antivirus, the only advice is still that, adding the app folder to the anti-virus software's whitelist.

**Comment by NoAvalon** [comment]
I see so there's no easy solution for it. No worries then. I just wanted to let you know about it. In any case, I'll just have it whitelisted then.
