### ISSUE TITLE
[Bug]: Space Ishtar's 2nd Skill becomes Single Target after a few offensive buffs

### ISSUE THREAD

**Issue by Solitare9** [chaldea-center/chaldea#87]
### What happened?

Laplace: The NP Damage Up portion of Space Ishtar's 2nd Skill (Venus Driver B) only affects the rightmost enemy after at least 3 other offensive buffs. I've tried targeting other enemies while using skills and her NP, but only the rightmost enemy takes increased damage. I made a team with 2 Caster Altrias (Castoria) and Space Ishtar (with a Kaleidoscope CE equipped for convenience). Use any 2 of the three's 1st skills (which apply 1 Attack buff each), then Venus Driver, and then Space Ishtar's NP. This will do equal damage to all enemies. Undo the NP, apply the 3rd Attack buff, then Space Ishtar's NP again. You will now see that the rightmost enemy has taken increased damage compared to the others for some reason.

Castoria's 3rd Skill (Sword of Selection EX) applies 2 buffs at once, but it only affects this bug if Venus Driver changed Space Ishtar's NP to Arts.
![FGO Chaldea App bug ~ Spishtar skill 2 Action](https://user-images.githubusercontent.com/129904625/229942895-96ddcfff-35be-4baf-aedf-d7516b552495.jpg)

The following Debug screenshot shows this bug in action. The rightmost enemy is first and has an npDamageBuff: 400 (that's 40.0%) The other 2 have npDamageBuff: 200 (that's 20.0%). Venus Driver gives a 20% NP Damage buff and Space Ishtar's NP also gives a 20% NP Damage buff before damage. The buff from the NP always applies, so we have a base 20%, but Venus Driver's 20% is only included for the rightmost enemy.
![FGO Chaldea App bug ~ Spishtar skill 2 debug](https://user-images.githubusercontent.com/129904625/229943964-05c16b26-4248-4bb6-9eea-819005c41caf.jpg)

I've had this problem on both Android and Windows. I've tried many different battles, Mystic Codes, Craft Essences, and it's consistent. I've never written one of these before, so I hope it's helpful.

### Platform

All

### Device Info

Android 10, Windows 10 Home 22H2

### App Version

(2.3.0+923) 8afd0b

**Comment by SharpnelXu** [comment]
Hi, thanks for reporting this issue. Any feedback for Laplace is greatly appreciated, especially bug reports!

I took a look into this, and the root cause was due to a misplaced buff execution whenever Space Ishtar kills an enemy (type `functionDeadattack`, which is a buff that is called when an attacker's attack kills an enemy).

This is a generic bug related to not only Space Ishtar, but also any buffs with limited apply times. In the code logic, we clear buff status after each function execution, and the npDamageBuff granted by Space Ishtar's second skill can only be applied once, so it gets cleared after the buff execution mentioned above.

I have removed this buff execution from the damage calculation logic and placed it after player card execution, which should fix this issue.
